groups:
  forex:
    - AUDCAD
    - AUDCHF
    - AUDJPY
    - AUDNZD
    - AUDSGD
    - AUDUSD
    - CADCHF
    - CADJPY
    - CADSGD
    - CHFJPY
    - CHFSEK
    - CHFSGD
    - EURAUD
    - EURCAD
    - EURCHF
    - EURCZK
    - EURGBP
    - EURHUF
    - EURJPY
    - EURNOK
    - EURNZD
    - EURPLN
    - EURSEK
    - EURSGD
    - EURUSD
    - EURZAR
    - GBPAUD
    - GBPCAD
    - GBPCHF
    - GBPJPY
    - GBPMXN
    - GBPNOK
    - GBPNZD
    - GBPSEK
    - GBPSGD
    - GBPUSD
    - MXNJPY
    - NOKJPY
    - NOKSEK
    - NZDCAD
    - NZDCHF
    - NZDJPY
    - NZDUSD
    - SGDJPY
    - USDCAD
    - USDCHF
    - USDCNH
    - USDCZK
    - USDHUF
    - USDINR
    - USDJPY
    - USDMXN
    - USDNOK
    - USDPLN
    - USDRON
    - USDSEK
    - USDSGD
    - USDTHB
    - USDZAR
    - ZARJPY
    - USDHKD
    - USDBRL
    - USDCLP
    - USDCOP
    - USDIDR
    - USDKRW
    - USDTWD
    - USDUSC
    - USDCAC
    - USDCHC
    - USDSGC
    - EUCUSD
    - USDJPC

  commodities:
    - XAUUSD
    - XAUEUR
    - XAUAUD
    - XAUGBP
    - XAGUSD
    - XPTUSD
    - BRENT.fs
    - WTI.fs
    - UKOIL
    - USOIL
    - NATGAS.fs
    - SOYBEAN.fs
    - COCOA.fs
    - COFFEE.fs
    - COPPER.fs

  indices:
    - AUS200
    - CN50
    - EU50
    - FRA40
    - HK50
    - JPN225
    - US30
    - GER40
    - IT40
    - SGFREE
    - SWI20
    - SPA35
    - UK100
    - US500
    - US2000
    - USTECH
    - NETH25
    - CAC40.fs
    - CHINA50.fs
    - EUSTX50.fs
    - HSI.fs
    - NAS100.fs
    - NK225.fs
    - S&P.fs
    - SPI200.fs
    - DAX40.fs
    - DJ30.fs
    - FT100.fs
    - USDINDEX.fs
    - VIX.fs

  crypto:
    # Major Cryptos (USD)
    - BTCUSD
    - ETHUSD
    - BCHUSD
    - LTCUSD
    - XRPUSD
    - ADAUSD
    - DOTUSD
    - XLMUSD
    - DOGUSD
    - LNKUSD
    # DeFi & Alt (USD)
    - SOL-USD
    - AVAX-USD
    - AAVE-USD
    - UNI-USD
    - SUSHI-USD
    - COMP-USD
    - CRV-USD
    - LRC-USD
    - MANA-USD
    - SAND-USD
    - BAT-USD
    - BNB-USD
    - KSM-USD
    - XTZ-USD
    # JPY Pairs
    - BCH-JPY
    - BTC-JPY
    - ETH-JPY
    - LNK-JPY
    - LTC-JPY
    - XRP-JPY